SuperNetSetting: # 超网配置
  - [4, 8, 12, 16] # 1
  - [4, 8, 12, 16] # 2
  - [4, 8, 12, 16] # 3
  - [4, 8, 12, 16] # 4
  - [4, 8, 12, 16] # 5
  - [4, 8, 12, 16] # 6
  - [4, 8, 12, 16] # 7
  - [4, 8, 12, 16, 20, 24, 28, 32] # 8
  - [4, 8, 12, 16, 20, 24, 28, 32] # 9
  - [4, 8, 12, 16, 20, 24, 28, 32] # 10
  - [4, 8, 12, 16, 20, 24, 28, 32] # 11
  - [4, 8, 12, 16, 20, 24, 28, 32] # 12
  - [4, 8, 12, 16, 20, 24, 28, 32] # 13
  - [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64] # 14
  - [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64] # 15
  - [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64] # 16
  - [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64] # 17
  - [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64] # 18
  - [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64] # 19
  - [4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64] # fc

# 训练脚本
config: configs/meta.yml
track_file: Track1_200_archs.json
save_dir: record
dataset: cifar100
# support cifar100 or cifar10

epochs: 300
batch_size: 2048
learning_rate: 0.1
num_workers: 3
model_type: dla
finetune: false
distill: false

# data augmentation
cutout: 0.5
mixup: true
mixup_alpha: 0.4

momentum: 0.9
weight_decay: 0.0005
seed: 0

report_freq: 2
gpu: 0

# 算法细节
sandwich_N: 3
